### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by vanarok** [Capelinha/Steam-easy-switch#1]
Each time requires a password, readme read

**Comment by Capelinha** [comment]
Hi, in the last update of Steam I had to log in to my accounts again. Did you click "remember my password"? You need to save the password on all your accounts for the steam to save your credentials.

[https://i.imgur.com/U73U04x.png](https://i.imgur.com/U73U04x.png)

**Comment by vanarok** [comment]
Yes, I read the instructions. Unfortunately, this is my Steam buggy and does not save the session.
